it-at-m/refarch

refarch-gateway/pom.xml

Revert "Update dependency com.diffplug.spotless:spotless-maven-plugin to v2.43.0"

---

.github/CODEOWNERS

Take over CODEOWNERS from https://github.com/it-at-m/refarch-templates/blob/main/.github/CODEOWNERS

:construction_worker: add CODEOWNERS file

---

refarch-gateway/pom.xml

Rename pom vars to match internal naming convention.

:recycle: rename pom vars

---

refarch-gateway/src/main/resources/logback-spring.xml

Rename `json-logger` profile to `json-logging` to match README

:boom: gateway rename json logging profile

---

.github/workflows/maven.yaml

Fix s3-integration-rest-service image build after package rename

:bug: ci fix s3-integration-rest-service image build

---

pom.xml

Root pom add missing properties for release.

:bug: root pom fix missing release properties

---

renovate.json
renovate.json5

- Updated Renovate configuration to be identical to https://github.com/it-at-m/refarch-templates
**Reference**
Issues #89

:wrench: Update Renovate configuration

---

.github/workflows/codeql.yaml

- Added custom CodeQL workflow (advanced configuration)
- Disabled simple CodeQL workflow
**Reference**
Issues #137

Added custom CodeQL workflow

---

refarch-gateway/pom.xml

Fix gateway image missing main manifest.
**Reference**
Issues closes #141

:bug: gateway re add missing spring-boot-maven-plugin

---

renovate.json5

- Updated renovate configuration to ignore some major updates not relevant for company infrastructure and tooling (need to keep manually in sync in future)
**Reference**
Issues #148

:wrench: Updated renovate configuration

---

refarch-gateway/README.md

add profiles

---

.github/README.md

Update reference to refarch-templates in README.md

Update readme templates reference

---

refarch-integrations/refarch-s3-integration/refarch-s3-integration-rest/refarch-s3-integration-rest-starter/src/main/java/de/muenchen/refarch/integration/s3/configuration/S3IntegrationRestAutoConfiguration.java
refarch-integrations/refarch-s3-integration/refarch-s3-integration-starter/src/main/java/de/muenchen/refarch/integration/s3/configuration/S3IntegrationAutoConfiguration.java

Add missing component scans to s3-starter and s3-rest-starter.
Fixes missing rest endpoints.

:bug: s3 starter add missing component scan

---

refarch-gateway/src/main/resources/application-local.yml

Fix typo in local example route
**Reference**
Issues closes #177

:pencil2: gateway fix local config typo in example route

---

refarch-gateway/README.md
refarch-gateway/src/main/resources/application-local.yml
refarch-gateway/src/main/resources/application.yml

Refactor gateway default oauth2 config to fix `no-security` profile.
**Reference**
Issues closes #193

:bug: gateway refactor default oauth2 config

---

.github/README.md

Document main technologies of RefArch.
**Reference**
Issues closes #47

Update README.md add built with

---

.github/actions/retag-image/action.yaml
.github/workflows/retag_image.yaml

Add workflow for retagging image.

:sparkles: ci add retag image workflow

---

refarch-tools/refarch-java-tools/pom.xml

Remove refarch-java-tools spring parent.
**Reference**
Issues closes #254

:heavy_minus_sign: refarch-java-tools rm spring parent

---

refarch-gateway/pom.xml
refarch-integrations/pom.xml
refarch-tools/refarch-java-tools/pom.xml

Add missing url to pom.
Should fix failing release for refarch-tools

:bug: pom add missing url

---

docs/package-lock.json

- Regenerated lockfile
**Reference**

:pushpin: Regenerated lockfile

---

refarch-integrations/refarch-dms-integration/refarch-dms-integration-fabasoft-rest-api/src/main/api/api-docs.json

[documentation-link]: https://refarch.oss.muenchen.de/templates/document.html#writing-the-documentation
[code-quality-link]: https://refarch.oss.muenchen.de/templates/develop.html#code-quality
[refarch-templates-create-issue-link]: https://github.com/it-at-m/refarch-templates/issues/new/choose
- Update dms-rest-client API spec to v 1.2.0
**Note**: If some checklist items are not relevant for your PR, just remove them.

maint/dms rest bump api spec to 1.2.0
